use std::{
    fs,
    io::Write,
    path::{Path, PathBuf},
};

use flate2::{Compression, GzBuilder};

fn main() -> Result<(), Box<dyn std::error::Error>> {
    println!("cargo:rustc-check-cfg=cfg(xp_missing_web_dist)");

    let protoc_path: PathBuf = protoc_bin_vendored::protoc_bin_path()?;
    unsafe {
        std::env::set_var("PROTOC", protoc_path);
    }

    let proto_root = "proto/xray";
    let protos = [
        "proto/xray/app/proxyman/config.proto",
        "proto/xray/app/proxyman/command/command.proto",
        "proto/xray/app/router/config.proto",
        "proto/xray/app/router/command/command.proto",
        "proto/xray/app/stats/command/command.proto",
        "proto/xray/common/net/address.proto",
        "proto/xray/common/net/network.proto",
        "proto/xray/common/net/port.proto",
        "proto/xray/common/protocol/user.proto",
        "proto/xray/common/protocol/server_spec.proto",
        "proto/xray/common/serial/typed_message.proto",
        "proto/xray/core/config.proto",
        "proto/xray/proxy/shadowsocks_2022/config.proto",
        "proto/xray/proxy/vless/account.proto",
        "proto/xray/proxy/vless/inbound/config.proto",
        "proto/xray/proxy/vless/outbound/config.proto",
        "proto/xray/proxy/socks/config.proto",
        "proto/xray/proxy/freedom/config.proto",
        "proto/xray/transport/internet/config.proto",
        "proto/xray/transport/internet/reality/config.proto",
        "proto/xray/transport/internet/splithttp/config.proto",
        "proto/xray/transport/internet/tcp/config.proto",
    ];

    for proto in protos {
        println!("cargo:rerun-if-changed={proto}");
    }

    tonic_prost_build::configure()
        .build_client(true)
        .build_server(true)
        .compile_protos(&protos, &[proto_root])?;

    let history_sync_proto = "proto/history_sync.proto";
    println!("cargo:rerun-if-changed={history_sync_proto}");
    tonic_prost_build::configure()
        .build_client(false)
        .build_server(false)
        .compile_protos(&[history_sync_proto], &["proto"])?;

    embed_web_dist()?;

    Ok(())
}

fn embed_web_dist() -> Result<(), Box<dyn std::error::Error>> {
    let manifest_dir = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR")?);
    let dist_dir = manifest_dir.join("web").join("dist");
    let out_dir = PathBuf::from(std::env::var("OUT_DIR")?);
    let out_file = out_dir.join("embedded_web_assets.rs");

    // Ensure cargo rebuilds when web assets change.
    println!("cargo:rerun-if-changed=web/dist");
    println!("cargo:rerun-if-changed=web/dist/assets");

    let index_html = dist_dir.join("index.html");
    if !index_html.is_file() {
        println!("cargo:rustc-cfg=xp_missing_web_dist");
        println!(
            "cargo:warning=missing web/dist/index.html at {index_html:?}; run `cd web && bun run build`"
        );
        write_embedded_assets_module(&out_file, &[])?;
        return Ok(());
    }

    let mut files: Vec<PathBuf> = Vec::new();
    collect_files_recursively(&dist_dir, &mut files)?;
    files.sort();

    let compressed_dir = out_dir.join("embedded_web_assets");
    fs::create_dir_all(&compressed_dir)?;

    let mut entries: Vec<(String, String, bool)> = Vec::new();
    for (index, file) in files.into_iter().enumerate() {
        let rel = file.strip_prefix(&dist_dir)?;
        if rel.as_os_str().is_empty() {
            continue;
        }

        let rel_str = rel
            .to_string_lossy()
            .replace('\\', "/")
            .trim_start_matches('/')
            .to_string();
        let include_suffix = format!("/web/dist/{rel_str}");

        println!("cargo:rerun-if-changed=web/dist/{rel_str}");
        if should_gzip(&file) {
            let compressed_name = format!("{index}.gz");
            let compressed_path = compressed_dir.join(&compressed_name);
            let source = fs::read(&file)?;
            let mut encoder = GzBuilder::new()
                .mtime(0)
                .write(Vec::new(), Compression::best());
            encoder.write_all(&source)?;
            fs::write(&compressed_path, encoder.finish()?)?;
            entries.push((
                rel_str,
                format!("/embedded_web_assets/{compressed_name}"),
                true,
            ));
        } else {
            entries.push((rel_str, include_suffix, false));
        }
    }

    write_embedded_assets_module(&out_file, &entries)?;
    Ok(())
}

fn write_embedded_assets_module(
    out_file: &Path,
    entries: &[(String, String, bool)],
) -> Result<(), Box<dyn std::error::Error>> {
    let mut src = String::new();
    src.push_str("// @generated by build.rs; do not edit.\n");
    src.push_str("#[derive(Clone, Copy)]\n");
    src.push_str("pub struct EmbeddedAsset {\n");
    src.push_str("    pub bytes: &'static [u8],\n");
    src.push_str("    pub gzip: bool,\n");
    src.push_str("}\n");
    src.push_str("#[allow(clippy::all)]\n");
    src.push_str("pub fn get(path: &str) -> Option<EmbeddedAsset> {\n");
    src.push_str("    match path {\n");
    for (rel_path, include_suffix, gzip) in entries {
        let include_root = if *gzip {
            "OUT_DIR"
        } else {
            "CARGO_MANIFEST_DIR"
        };
        src.push_str(&format!(
            concat!(
                "        {rel_path:?} => Some(EmbeddedAsset {{ bytes: ",
                "&include_bytes!(concat!(env!({include_root:?}), {include_suffix:?}))[..], ",
                "gzip: {gzip} }}),\n"
            ),
            rel_path = rel_path,
            include_root = include_root,
            include_suffix = include_suffix,
            gzip = gzip
        ));
    }
    src.push_str("        _ => None,\n");
    src.push_str("    }\n");
    src.push_str("}\n");

    fs::write(out_file, src)?;
    Ok(())
}

fn should_gzip(path: &Path) -> bool {
    matches!(
        path.extension().and_then(|extension| extension.to_str()),
        Some("css" | "html" | "js" | "json" | "map" | "svg" | "txt" | "webmanifest")
    )
}

fn collect_files_recursively(dir: &Path, out: &mut Vec<PathBuf>) -> Result<(), std::io::Error> {
    for entry in fs::read_dir(dir)? {
        let entry = entry?;
        let path = entry.path();
        let meta = entry.metadata()?;
        if meta.is_dir() {
            collect_files_recursively(&path, out)?;
        } else if meta.is_file() {
            out.push(path);
        }
    }
    Ok(())
}
